apiVersion: v1
kind: Service
metadata:
  name: es-discovery
  namespace: skywalking
  labels:
    app: es-discovery
spec:
  type: ClusterIP
  ports:
  - port: 9200
    name: rest
  - port: 9300
    name: grpc
  selector:
    app: es
