apiVersion: v1
kind: Service
metadata:
  name: sw-oap-svc-http
  namespace: skywalking
  labels:
    service: sw-oap-svc-http
spec:
  ports:
  - port: 12800
    name: rest
  - port: 1234
    name: page
  selector:
    app: sw-oap